import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";

import AutoTradeControls from "../components/auto-trading/AutoTradeControls";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Zap, Activity, DollarSign, Target, Play, Pause } from 'lucide-react';

export default function AutoTrading() {
  const [settings, setSettings] = useState(null);
  const [autoTrades, setAutoTrades] = useState([]);
  const [cashoutHistory, setCashoutHistory] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [stats, setStats] = useState({
    totalAutoTrades: 0,
    totalCashouts: 0,
    totalProfit: 0,
    successRate: 0
  });

  useEffect(() => {
    loadSettings();
    loadAutoTrades();
    loadCashoutHistory();
  }, []);

  const loadSettings = async () => {
    try {
      const settingsList = await base44.entities.AutoTradeSettings.list();
      if (settingsList.length > 0) {
        setSettings(settingsList[0]);
      } else {
        const defaultSettings = await base44.entities.AutoTradeSettings.create({
          enabled: false,
          take_profit_percentage: 5.0,
          stop_loss_percentage: 2.0,
          auto_cashout_enabled: false,
          cashout_percentage: 50.0,
          min_profit_to_cashout: 100.0,
          max_position_size: 1000.0,
          trading_pairs: ['BTC/USDT']
        });
        setSettings(defaultSettings);
      }
    } catch (error) {
      console.error("Error loading settings:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const loadAutoTrades = async () => {
    try {
      // Get trades generated by auto trading
      const trades = await base44.entities.Trade.filter({ strategy: 'auto_trade' }, "-created_date", 50);
      setAutoTrades(trades);
      
      // Calculate stats
      const totalProfit = trades.reduce((sum, trade) => sum + (trade.profit_loss || 0), 0);
      const winningTrades = trades.filter(trade => (trade.profit_loss || 0) > 0).length;
      const successRate = trades.length > 0 ? (winningTrades / trades.length) * 100 : 0;
      
      setStats(prev => ({
        ...prev,
        totalAutoTrades: trades.length,
        totalProfit,
        successRate
      }));
    } catch (error) {
      console.error("Error loading auto trades:", error);
    }
  };

  const loadCashoutHistory = async () => {
    try {
      const cashouts = await base44.entities.Transaction.filter({ type: 'auto_cashout' }, "-created_date", 20);
      setCashoutHistory(cashouts);
      
      const totalCashouts = cashouts.reduce((sum, cashout) => sum + cashout.amount, 0);
      setStats(prev => ({
        ...prev,
        totalCashouts: cashouts.length,
        totalCashedOut: totalCashouts
      }));
    } catch (error) {
      console.error("Error loading cashout history:", error);
    }
  };

  const handleUpdateSettings = async (newSettings) => {
    try {
      if (settings?.id) {
        await base44.entities.AutoTradeSettings.update(settings.id, newSettings);
      } else {
        const created = await base44.entities.AutoTradeSettings.create(newSettings);
        setSettings(created);
      }
      
    } catch (error) {
      console.error("Error updating settings:", error);
      throw error;
    }
  };


  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 flex items-center justify-center">
        <div className="text-white text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-green-400 mx-auto mb-4"></div>
          <p>Loading auto trading...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 p-6">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
            <Zap className="w-8 h-8" />
            Auto Trading
          </h1>
          <p className="text-slate-400">
            Automated trading with intelligent cashout management
          </p>
        </div>

        {/* Stats Overview */}
        <div className="grid md:grid-cols-4 gap-4 mb-8">
          <Card className="glass-card">
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-slate-400">Auto Trades</p>
                  <p className="text-2xl font-bold text-white">{stats.totalAutoTrades}</p>
                </div>
                <Activity className="w-8 h-8 text-blue-400" />
              </div>
            </CardContent>
          </Card>

          <Card className="glass-card">
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-slate-400">Success Rate</p>
                  <p className="text-2xl font-bold text-green-400">{stats.successRate.toFixed(1)}%</p>
                </div>
                <Target className="w-8 h-8 text-green-400" />
              </div>
            </CardContent>
          </Card>

          <Card className="glass-card">
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-slate-400">Total Profit</p>
                  <p className={`text-2xl font-bold ${stats.totalProfit >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                    {formatCurrency(stats.totalProfit)}
                  </p>
                </div>
                <DollarSign className="w-8 h-8 text-purple-400" />
              </div>
            </CardContent>
          </Card>

          <Card className="glass-card">
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-slate-400">Cashouts</p>
                  <p className="text-2xl font-bold text-white">{stats.totalCashouts}</p>
                </div>
                <DollarSign className="w-8 h-8 text-orange-400" />
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="grid lg:grid-cols-3 gap-6">
          {/* Auto Trading Controls - Takes 2/3 width */}
          <div className="lg:col-span-2">
            <AutoTradeControls 
              settings={settings}
              onUpdateSettings={handleUpdateSettings}
              isLoading={isLoading}
            />
          </div>

          {/* Activity Feed - Takes 1/3 width */}
          <div className="space-y-6">
            {/* Recent Auto Trades */}
            <Card className="glass-card">
              <CardHeader className="pb-4">
                <CardTitle className="text-white flex items-center gap-2">
                  <Activity className="w-5 h-5" />
                  Recent Auto Trades
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3 max-h-64 overflow-y-auto">
                  {autoTrades.slice(0, 5).map((trade, index) => (
                    <div key={trade.id || index} className="flex items-center justify-between p-3 bg-slate-800/30 rounded-lg">
                      <div>
                        <div className="flex items-center gap-2">
                          <Badge className={trade.side === 'buy' ? 'bg-green-500/20 text-green-400' : 'bg-red-500/20 text-red-400'}>
                            {trade.side.toUpperCase()}
                          </Badge>
                          <span className="text-white font-medium">{trade.symbol}</span>
                        </div>
                        <div className="text-sm text-slate-400">
                          {formatCurrency(trade.total)}
                        </div>
                      </div>
                      <div className="text-right">
                        <div className={`font-semibold ${trade.profit_loss >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                          {trade.profit_loss >= 0 ? '+' : ''}{formatCurrency(trade.profit_loss || 0)}
                        </div>
                        <div className="text-xs text-slate-400">
                          {new Date(trade.created_date).toLocaleDateString()}
                        </div>
                      </div>
                    </div>
                  ))}
                  
                  {autoTrades.length === 0 && (
                    <div className="text-center text-slate-400 py-8">
                      <Activity className="w-12 h-12 mx-auto mb-2 opacity-50" />
                      <p>No auto trades yet</p>
                      <p className="text-sm">Enable auto trading to see activity here</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Auto Cashout History */}
            {settings?.auto_cashout_enabled && (
              <Card className="glass-card">
                <CardHeader className="pb-4">
                  <CardTitle className="text-white flex items-center gap-2">
                    <DollarSign className="w-5 h-5" />
                    Cashout History
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3 max-h-48 overflow-y-auto">
                    {cashoutHistory.slice(0, 5).map((cashout, index) => (
                      <div key={cashout.id || index} className="flex items-center justify-between p-3 bg-green-500/10 rounded-lg border border-green-500/20">
                        <div>
                          <div className="text-white font-medium">Auto Cashout</div>
                          <div className="text-sm text-slate-400">{cashout.notes}</div>
                        </div>
                        <div className="text-green-400 font-semibold">
                          +{formatCurrency(cashout.amount)}
                        </div>
                      </div>
                    ))}
                    
                    {cashoutHistory.length === 0 && (
                      <div className="text-center text-slate-400 py-6">
                        <DollarSign className="w-10 h-10 mx-auto mb-2 opacity-50" />
                        <p className="text-sm">No cashouts yet</p>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Quick Actions */}
            <Card className="glass-card">
              <CardHeader className="pb-4">
                <CardTitle className="text-white">Bot Control</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <Button 
                  variant="outline" 
                  className="w-full border-green-600 text-green-400 hover:bg-green-600 hover:text-white"
                >
                  <Play className="w-4 h-4 mr-2" />
                  Force Start Cycle
                </Button>
                <Button 
                  variant="outline" 
                  className="w-full border-red-600 text-red-400 hover:bg-red-600 hover:text-white"
                >
                  <Pause className="w-4 h-4 mr-2" />
                  Emergency Stop All
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}